import type { Metadata } from "next";
import "./globals.css";
import type { ReactNode } from "react";
import Navbar from "./components/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-background text-foreground">
        {/* Navbar */}
        <Navbar />
        {children}
      </body>
    </html>
  );
}
